export const API_INVOCATION = "API_INVOCATION";
export const SHOW_TOAST_MESSAGE = "SHOW_TOAST_MESSAGE";
export const RESET_SHOW_TOAST_MESSAGE = "RESET_SHOW_TOAST_MESSAGE";
export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";

export const GET_SEARCH_PRODUCT_LIST="GET_SEARCH_PRODUCT_LIST"
export const GET_SEARCH_PRODUCT_LIST_SUCCESS="GET_SEARCH_PRODUCT_LIST_SUCCESS"
export const GET_SEARCH_PRODUCT_LIST_ERROR="GET_SEARCH_PRODUCT_LIST_ERROR"
export const RESET_SEARCH_PRODUCT_LIST="RESET_SEARCH_PRODUCT_LIST"


export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR"


export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS"
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR"

export const STORE_PRODUCT_LIST = "STORE_PRODUCT_LIST"
export const STORE_PRODUCT_LIST_SUCCESS = "STORE_PRODUCT_LIST_SUCCESS"
export const STORE_PRODUCT_LIST_ERROR = "STORE_PRODUCT_LIST_ERROR"

export const GET_PRODUCT_ON_BASIS_OF_ID = "GET_PRODUCT_ON_BASIS_OF_ID"
export const GET_PRODUCT_ON_BASIS_OF_ID_SUCCESS = "GET_PRODUCT_ON_BASIS_OF_ID_SUCCESS"
export const GET_PRODUCT_ON_BASIS_OF_ID_ERROR = "GET_PRODUCT_ON_BASIS_OF_ID_ERROR"

export const UPDATE_PRODUCT_ON_BASIS_OF_ID = "UPDATE_PRODUCT_ON_BASIS_OF_ID"
export const UPDATE_PRODUCT_ON_BASIS_OF_ID_SUCCESS = "UPDATE_PRODUCT_ON_BASIS_OF_ID_SUCCESS"
export const UPDATE_PRODUCT_ON_BASIS_OF_ID_ERROR = "UPDATE_PRODUCT_ON_BASIS_OF_ID_ERROR"

